### PR TITLE
simplify patch for sncosmo support

### PR DESCRIPTION
**Pull request by mjuric**
Hi Scott,

I simplified your patch. It builds for me both on OS X and Linux, but could you try it out as well (just see if it still builds `sncosmo`)? This is to make sure I haven't forgotten something...

### CODE REVIEW

**Comment by danielsf** [comment]
Sure.  How do I remove an old build from my conda-lsst path?  If I try to rebuild lsst_sims (or sncosmo) on my machine as it is, it will just mark sncosmo as 'already built' and not try to do anything.

**Comment by mjuric** [comment]
Remove everything in `.../miniconda/conda-bld/osx-64/` and then rerun `conda index` in that directory. Then do the rebuild.

**Comment by danielsf** [comment]
That clean up method did not work.  It still just went through a list of all packages and marked them as 'already built'.

I will try creating a clean environment and doing the test build tonight (don't want to tie up my machine while I'm awake).

**Comment by mjuric** [comment]
@danielsf I think that's because it sees the packages on the /dev channel. Comment out the channel entry in ~/.condarc and I think it should work.

PS: You don't have to rebuild the whole thing -- just `sncosmo` was the problem (right)?

**Comment by danielsf** [comment]
that did it (commenting out the channel in .condarc)

sncosmo still builds

thanks

**Pull request merged**
